name: Build function on checkin

on: 
  push:
    paths:
      - 'modules/function/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Print the current branch name
        run: echo "$GITHUB_REF"

      - name: Check out branch
        uses: actions/checkout@main
        
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Build dotnet lambda solution
        run: dotnet build modules/function/gpconnect-appointment-checker.function.sln

      - name: Build docker lambda application image
        run: docker build -t gpconnect-appointment-checker-function-application modules/function/.
