# This is a basic workflow to help you get started with Actions

name: Database

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

env:
  DB_HOST: localhost
  DB_USERNAME: postgres
  DB_PASSWORD: postgres

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gpconnect
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5         
    
    steps:

      - uses: actions/checkout@v2

      - name: Check Postgres running
        run: PGPASSWORD=postgres psql -U postgres -d postgres -h localhost -c "SELECT version()"

      - name: Install flyway
        run: wget -qO- https://repo1.maven.org/maven2/org/flywaydb/flyway-commandline/6.5.6/flyway-commandline-6.5.6-linux-x64.tar.gz | tar xvz && sudo ln -s `pwd`/flyway-6.5.6/flyway /usr/local/bin 

      - name: Flyway migrate database schema 
        run: flyway -url=jdbc:postgresql://localhost/gpconnect -user=postgres -password=postgres -locations=filesystem:$GITHUB_WORKSPACE/database/schema migrate

      - name: Flyway install database functions 
        run: flyway -url=jdbc:postgresql://localhost/gpconnect -user=postgres -password=postgres -locations=filesystem:$GITHUB_WORKSPACE/database/functions migrate
